package appeng.core.localization;

import com.gtnewhorizon.gtnhlib.color.ColorResource;

public class ColorUtils {

    private static final ColorResource.Factory color = new ColorResource.Factory("ae2");

    public static final ColorResource
    // spotless:off
        guiTextColorGray                    = color.rgb("guiTextColorGray",                     "0x404040"),
        guiTextColorBlack                   = color.rgb("guiTextColorBlack",                    "0x000000"),
        searchboxText                       = color.rgb("searchboxText",                        "0xFFFFFF"),
        craftingStatusCPUName               = color.rgb("craftingStatusCPUName",                "0x202020"),
        craftingStatusCPUStorage            = color.rgb("craftingStatusCPUStorage",             "0x202020"),
        craftingStatusCPUAmount             = color.rgb("craftingStatusCPUAmount",              "0x202020"),
        craftAmountToCraft                  = color.rgb("craftAmountToCraft",                   "0xFFFFFF"),
        craftConfirmPercent25               = color.rgb("craftConfirmPercent25",                "0x1c4ca6"),
        craftConfirmPercent50               = color.rgb("craftConfirmPercent50",                "0x1a751e"),
        craftConfirmPercent75               = color.rgb("craftConfirmPercent75",                "0xe3940b"),
        craftConfirmPercent100              = color.rgb("craftConfirmPercent100",               "0x660f0f"),
        oreFilterTextLengthFull             = color.rgb("oreFilterTextLengthFull",              "0xff0000"),
        neiGrindstoneRecipeChance           = color.rgb("neiGrindstoneRecipeChance",            "0x000000"),
        neiGrindstoneNoSecondOutput         = color.rgb("neiGrindstoneNoSecondOutput",          "0x000000"),
        neiCellView                         = color.rgb("neiCellView",                          "0x000000"),
        cellStatusOrange                    = color.rgb("cellStatusOrange",                     "0xFBA900"),
        cellStatusRed                       = color.rgb("cellStatusRed",                        "0xFB0000"),
        cellStatusBlue                      = color.rgb("cellStatusBlue",                       "0x00AAFF"),
        cellStatusGreen                     = color.rgb("cellStatusGreen",                      "0x00FF00"),
        colorSelectBtnText                  = color.rgb("colorSelectBtnText",                   "0xFFFFFF"),
        reshuffleStatusBeforeSnapshot       = color.rgb("reshuffleStatusBeforeSnapshot",        "0xDDAA00"),
        reshuffleStatusAfterSnapshot        = color.rgb("reshuffleStatusAfterSnapshot",         "0x00AA00"),
        reshuffleStatusExtracting           = color.rgb("reshuffleStatusExtracting",            "0xDDAA00"),
        reshuffleStatusInjecting            = color.rgb("reshuffleStatusInjecting",             "0x00AA00"),
        reshuffleStatusComplete             = color.rgb("reshuffleStatusComplete",              "0x0055FF"),
        reshuffleStatusFailed               = color.rgb("reshuffleStatusFailed",                "0xCC0000"),
        reshuffleStatusCancelled            = color.rgb("reshuffleStatusCancelled",             "0xFF6600"),
        wirelessKitGood                     = color.rgb("wirelessKitGood",                      "0x7CFF4A"),
        wirelessKitNeutral                  = color.rgb("wirelessKitNeutral",                   "0xF99739"),
        wirelessKitBad                      = color.rgb("wirelessKitBad",                       "0xA50029"),

        searchboxFocused                    = color.argb("searchboxFocused",                    "0x6E000000"),
        searchboxUnfocused                  = color.argb("searchboxUnfocused",                  "0x00000000"),
        itemSlotOverlayUnpowered            = color.argb("itemSlotOverlayUnpowered",            "0x66111111"),
        itemSlotOverlayInvalid              = color.argb("itemSlotOverlayInvalid",              "0x66ff6666"),
        itemSlotOverlayFluidMismatch        = color.argb("itemSlotOverlayFluidMismatch",        "0x66FF0000"),
        craftConfirmMissingItem             = color.argb("craftConfirmMissingItem",             "0x1AFF0000"),
        craftingCPUActive                   = color.argb("craftingCPUActive",                   "0x5A45F021"),
        craftingCPUInactive                 = color.argb("craftingCPUInactive",                 "0x5AFFF7AA"),
        craftingCPUUnsupportedStack         = color.argb("craftingCPUUnsupportedStack",         "0x5AE07070"),
        craftingCPUSameNetwork              = color.argb("craftingCPUSameNetwork",              "0x5AE07070"),
        craftingCPUSomethingStuck           = color.argb("craftingCPUSomethingStuck",           "0x5AC9A53A"),
        craftingCPUNoTarget                 = color.argb("craftingCPUNoTarget",                 "0x5AE07070"),
        craftingPinSlotBackground           = color.argb("craftingPinSlotBackground",           "0x38E6731A"),
        playerPinSlotBackground             = color.argb("playerPinSlotBackground",             "0x00000000"),
        craftingDiagnosticTerminalLine      = color.argb("craftingDiagnosticTerminalLine",      "0x668C8C8C"),
        craftingDiagnosticTerminalRowHover  = color.argb("craftingDiagnosticTerminalRowHover",  "0x33808080"),
        searchHighlight                     = color.argb("searchHighlight",                     "0xFFFFFF55"),
        searchGoToHighlight                 = color.argb("searchGoToHighlight",                 "0xFFFFAA00"),
        processBarStartColor                = color.argb("processBarStartColor",                "0xFFE60A00"),
        processBarMiddleColor               = color.argb("processBarMiddleColor",               "0xFFE6E600"),
        processBarEndColor                  = color.argb("processBarEndColor",                  "0xFF0AE600"),
        colorSelectBackground               = color.argb("colorSelectBackground",               "0xFF000000"),
        colorSelectBorder                   = color.argb("colorSelectBorder",                   "0xFFC6C6C6"),
        colorSelectBtnBg                    = color.argb("colorSelectBtnBg",                    "0xFF8B8B8B"),
        colorSelectBtnBorderSelected        = color.argb("colorSelectBtnBorderSelected",        "0xFF38de38"),
        colorSelectBtnBorderHover           = color.argb("colorSelectBtnBorderHover",           "0xFFFFFFFF"),
        colorSelectBtnBorder                = color.argb("colorSelectBtnBorder",                "0xFF000000"),
        colorSelectBtnBorderDisabled        = color.argb("colorSelectBtnBorderDisabled",        "0xFF555555"),
        colorSelectBtnOverlayDisabled       = color.argb("colorSelectBtnOverlayDisabled",       "0xB0000000"),
        colorSelectBtnOverlayHover          = color.argb("colorSelectBtnOverlayHover",          "0x80FFFFFF"),
        reshuffleProgressBorder             = color.argb("reshuffleProgressBorder",             "0xFF333333"),
        reshuffleProgressBackground         = color.argb("reshuffleProgressBackground",         "0xFF111111"),
        reshuffleProgressFillStart          = color.argb("reshuffleProgressFillStart",          "0xFF00FFFF"),
        reshuffleProgressFillEnd            = color.argb("reshuffleProgressFillEnd",            "0xFF00FF00"),
        reshuffleProgressMarker             = color.argb("reshuffleProgressMarker",             "0xFFFFFFFF"),
        reshuffleScanRowHover               = color.argb("reshuffleScanRowHover",               "0x80FFFF00"),
        cellHealthOk                        = color.argb("cellHealthOk",                        "0xFF00CC44"),
        cellHealthWarn                      = color.argb("cellHealthWarn",                      "0xFFFFAA00"),
        cellHealthCrit                      = color.argb("cellHealthCrit",                      "0xFFFF2222"),
        cellHealthBarBackground             = color.argb("cellHealthBarBackground",             "0xFF222222"),
        colorButtonOutline                  = color.argb("colorButtonOutline",                  "0xFF404040"),
        networkVisualiserFloatingText       = color.argb("networkVisualiserFloatingText",       "0xffffffff"),
        networkVisualiserNodeMissing        = color.argb("networkVisualiserNodeMissing",        "0xffff0000"),
        networkVisualiserNodeDense          = color.argb("networkVisualiserNodeDense",          "0xffffff00"),
        networkVisualiserNodeProxy          = color.argb("networkVisualiserNodeProxy",          "0xffffa500"),
        networkVisualiserNodeDefault        = color.argb("networkVisualiserNodeDefault",        "0xff0000ff"),
        networkVisualiserLinkCompressed     = color.argb("networkVisualiserLinkCompressed",     "0xffff00ff"),
        networkVisualiserLinkDense          = color.argb("networkVisualiserLinkDense",          "0xffffff00"),
        networkVisualiserLinkProxy          = color.argb("networkVisualiserLinkProxy",          "0xffffa500"),
        networkVisualiserLinkDefault        = color.argb("networkVisualiserLinkDefault",        "0xff0000ff");
    // spotless:on
}
